server:
  port: 8080

spring:
  # put init data (from data.sql)
  sql:
    init:
      mode: always
  # get config properties from .env file
  config:
    import: optional:file:.env[.properties]
  # database
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

host:
  url:
    me: ${CONCERT_SERVER_URL}
    queue-server: ${QUEUE_SERVER_URL}