spring:
  profiles:
    active: local

# monitoring
server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus