global:
  scrape_interval: 10s  # metric 정보 수집 주기

scrape_configs:
  - job_name: "queue-server"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]